auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: wilson
url: http://king1991wbs.github.com/wilson
feed: /atom.xml
author_info: <a href="http://king1991wbs.github.com/wilson/">wilson</a>
