auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: wilson
url: https://king1991wbs.github.io/wilson
feed: /atom.xml
author_info: <a href="https://king1991wbs.github.io/wilson/">wilson</a>
